name: CI

on:
  push

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cortex:
    name: Cortex-M
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: thumbv7m-none-eabi
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-arm
          rustc --version
          qemu-system-arm --version
          lsb_release -a
      # - run: cargo run --release
      #   working-directory: tests/cortex
      #   continue-on-error: true
      - run: cargo run --release --features used_linker
        working-directory: tests/cortex
